### PR TITLE
migrate from lecture_i2ml pr 826

### PR DESCRIPTION
**Pull request by lisa-wm**

### CODE REVIEW

**Review by ludwigbothmann — CHANGES_REQUESTED** [review]
- the checks fail, could you look into this @lisa-wm ? The same for all the other PRs
- @patricio, could you add the pdf again?
Thank you both :pray:

**Comment by lisa-wm** [comment]
yeah, I just realized the workflow files are different from the old repo, so GH seems to be running the wrong checks (probably bc I cloned from template), but I'm not sure how actions have been handled lately. I'll find out and fix it

**Comment by lisa-wm** [comment]
BB says (see MM, lecture_i2ml): we disabled the checks and are waiting for a better solution (short-term to mid-term future). for now, the outdated workflows here will be removed.

**Comment by patriciomassaro** [comment]
[IC solutions SL](https://trello.com/c/62sCOyAY/219-ic-solutions-sl)

**Review by ludwigbothmann — APPROVED** [review]

**Review by ludwigbothmann — APPROVED** [review]

**Review by ludwigbothmann — COMMENTED** [review]
:+1:

**Pull request merged**
